title: Jekyll Test
email: cout.sngtech@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A github page to test Jekyll and Ruby.
  Uses the Bundler from Ruby and different plugins to format docs.
github_username:  SNGTech

domain: jekyll-test.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://jekyll-test.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /jekyll-test               # place folder name if the site is served in a subfolder

# Build settings
theme: minima

markdown: gfm

plugins: 
  - jekyll-titles-from-headings
  - jekyll-gfm-admonitions

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
